version: '3'

services:
  # backend:
  #   image: backend
  #   build:
  #     context: .
  #     dockerfile: backend\Dockerfile
  smtp:
    image: jeanberu/mailcatcher
    environment:
      - SMTP_PORT=1025
      - HTTP_PORT=1080
    ports:
      - "1025:1025"
      - "1080:1080"