
export const REQUEST_MOVIES = 'REQUEST_MOVIES';
export const REQUEST_MOVIES_SUCCESS = 'REQUEST_MOVIES_SUCCESS';
export const REQUEST_MOVIES_ERROR = 'REQUEST_MOVIES_ERROR';

export const DELETE_MOVIES = "DELETE_MOVIES";
export const DELETE_MOVIES_SUCCESS = "DELETE_MOVIES_SUCCESS";
export const DELETE_MOVIES_ERROR = "DELETE_MOVIES_ERROR";
export const SORT_MOVIE_BY_DATE_END = 'SORT_MOVIE_BY_DATE_END';
export const SORT_MOVIE_BY_TITLE_END = 'SORT_MOVIE_BY_TITLE_END';
export const SEARCH_MOVIES_FULL = "SEARCH_MOVIES_FULL";
export const SEARCH_MOVIES_FULL_END = "SEARCH_MOVIES_FULL_END";
export const CREATE_MOVIES = "CREATE_MOVIES";
export const CREATE_MOVIES_SUCCESS = "CREATE_MOVIES_SUCCESS";
export const CREATE_MOVIES_ERROR = "CREATE_MOVIES_ERROR";

export const ON_CHANGE_INPUT_TITLE = 'ON_CHANGE_INPUT_TITLE';
export const ON_CHANGE_INPUT_COVER = 'ON_CHANGE_INPUT_COVER';
export const ON_CHANGE_INPUT_BOXDATE = 'ON_CHANGE_INPUT_BOXDATE';

export const REQUEST_ACTORS = 'REQUEST_ACTORS';
export const REQUEST_ACTORS_ERROR = 'REQUEST_ACTORS_ERROR';
export const REQUEST_ACTORS_SUCCESS = 'REQUEST_ACTORS_SUCCESS';

export const REQUEST_REALISATORS = 'REQUEST_REALISATORS';
export const REQUEST_REALISATORS_ERROR = 'REQUEST_REALISATORS_ERROR';
export const REQUEST_REALISATORS_SUCCESS = 'REQUEST_REALISATORS_SUCCESS';
export const ON_CHANGE_INPUT_ACTOR = 'ON_CHANGE_INPUT_ACTOR';
export const ON_CHANGE_INPUT_REALISATOR = 'ON_CHANGE_INPUT_REALISATOR';

export const REQUEST_MOVIE = 'REQUEST_MOVIE';
export const REQUEST_MOVIE_SUCCESS = 'REQUEST_MOVIE_SUCCESS';
export const REQUEST_MOVIE_ERROR = 'REQUEST_MOVIE_ERROR';

export const EDIT_MOVIES = "EDIT_MOVIES";
export const EDIT_MOVIES_SUCCESS = "EDIT_MOVIES_SUCCESS";
export const EDIT_MOVIES_ERROR = "EDIT_MOVIES_ERROR";
